---
dependencies:
  - name: doccano-postgres
    version: "9.6"
    repository: file://deps/doccano-postgres
  - name: doccano-rabbitmq
    version: "3.8"
    repository: file://deps/doccano-rabbitmq

