apiVersion: v1
kind: Service
metadata:
  name: postgres-doccano
  namespace: {{ .Values.global.store_namespace | default "store" }}
spec:
  selector:
    app-name: postgres-doccano
  ports:
    - port: 5432
      targetPort: 5432