---
apiVersion: v1
kind: Service
metadata:
  name: dcm4chee-service
  namespace: {{ .Values.global.store_namespace }}
  labels:
    app-name: dcm4chee
spec:
  selector:
    app-name: dcm4chee
  type: ClusterIP
  ports:
  - name: dcm4che-http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: dcm4che-https
    port: 6443
    targetPort: 6443
    protocol: TCP
  - name: dcm4che-admin
    port: 9990
    targetPort: 9990
    protocol: TCP
  - name: dcm4che-dcm-port
    port: 11115
    targetPort: 11112
    protocol: TCP
  - name: dcm4che-hl7-port
    port: 2575
    targetPort: 2575
    protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rewrite-pacs
  namespace: {{ .Values.global.store_namespace }}
spec:
  replacePath:
    path: /dcm4chee-arc/ui2
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: dcm4chee-ingress-ip
  namespace: {{ .Values.global.store_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /dcm4chee-arc
        pathType: ImplementationSpecific
        backend:
          service:
            name: dcm4chee-service
            port:
              name: dcm4che-http
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: dcm4chee-ing-ip-rewrite
  namespace: {{ .Values.global.store_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: store-rewrite-pacs@kubernetescrd,kube-system-errorpages@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /pacs
        pathType: ImplementationSpecific
        backend:
          service:
            name: dcm4chee-service
            port:
              name: dcm4che-http
---