---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: keycloak
  template:
    metadata:
      labels:
        app-name: keycloak
    spec:
      initContainers:
      - name: init
        image: {{  .Values.global.registry_url }}/service_checker:1.1
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        env:
          - name: WAIT
            value: "postgres,postgres-keycloak-service.kube-system.svc,5432"
          - name: DELAY
            value: "2"
          - name: TIMEOUT
            value: "10"
      containers: 
        - name: keycloak-container
          image: {{  .Values.global.registry_url }}/keycloak:16.1.1
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          env:
          - name: KEYCLOAK_IMPORT
            value: /import/kaapana-realm.json
          - name: KEYCLOAK_USER
            value: {{ .Values.global.credentials.keycloak_admin_username }}
          - name: KEYCLOAK_PASSWORD
            value: {{ .Values.global.credentials.keycloak_admin_password }}
          - name: DB_VENDOR
            value: "postgres"
          - name: DB_ADDR
            value: "postgres-keycloak-service.kube-system.svc"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "keycloak"
          - name: DB_PASSWORD
            value: "keycloak"
          - name: DB_DATABASE
            value: "keycloak"
          - name: KEYCLOAK_HTTP_PORT
            value: "8080"
          - name: KEYCLOAK_HTTPS_PORT
            value: "8443"
          - name: ROOT_LOGLEVEL
            value: "DEBUG"
          - name: KEYCLOAK_LOGLEVEL
            value: "DEBUG"
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
          - name: admin
            containerPort: 9990
          resources:
            requests:
              memory: 600Mi
            limits:
              memory: 700Mi
          volumeMounts:
            - name: keycloak-realm
              mountPath: /import
            - name: ssl-config-files
              mountPath: /etc/x509/https
              readOnly: true
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 20
      volumes:
      - name: keycloak-realm
        configMap:
          name: keycloak-config
      - name: ssl-config-files
        secret:
          secretName: certificate
      imagePullSecrets:
      - name: registry-secret
---
