apiVersion: v1
kind: Service
metadata:
  name: doccano-rabbitmq
  namespace: {{ .Values.global.store_namespace | default "store" }}
spec:
  selector:
    app-name: doccano-rabbitmq
  ports:
    - port: 5672
      targetPort: 5672