---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: traefik-ingress-controller
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-system
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
<<<<<<< HEAD
          image: {{  .Values.global.registry_url }}/traefik:v2.3
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
=======
          image: {{  .Values.global.registry_url }}/traefik:v2.6
>>>>>>> develop
          args:
            - '--api.insecure'
            - '--accesslog'
            - '--providers.kubernetesingress'
            - '--providers.kubernetescrd'
            - '--providers.file.filename=/config/conf.toml'
            - '--providers.file.watch=true'
<<<<<<< HEAD
            - '--entrypoints.web.address=:80'
            # - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
            # - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
            - '--entrypoints.websecure.address=:443'
=======
            - '--entrypoints.web.address=:8000'
            - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
            - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
            - '--entrypoints.websecure.address=:4443'
>>>>>>> develop
            - '--entryPoints.websecure.http.tls=true'
            - '--entrypoints.dicom.Address=:11112'
            # - '--serversTransport.insecureSkipVerify=true'
            - '--api=true'
            - '--api.dashboard=true'
            - '--api.insecure=true'
            - '--api.debug=false'
            - '--log.level=WARN'
            - '--accesslog=true'
            - '--accesslog.filepath=/log/access.log'
            - '--log.format=json'
            - '--metrics=true'
            - '--metrics.prometheus=true'
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 500Mi
          volumeMounts:
            - mountPath: /config/conf.toml
              name: traefik-config-file
              subPath: conf.toml
            - mountPath: /log
              name: traefiklog
            - mountPath: /ssl
              name: ssl
      volumes:
        - name: traefiklog
          hostPath:
            path: {{ .Values.global.fast_data_dir }}/traefik
            type: DirectoryOrCreate
        - name: traefik-config-file
          configMap:
            name: traefik-config
            items:
            - key: conf.toml
              path: conf.toml
        - name: ssl
          secret:
            secretName: certificate
      imagePullSecrets:
      - name: registry-secret
---