---
apiVersion: v1
kind: Service
metadata:
  name: elastic-logging-service
  namespace: {{ .Values.global.monitoring_namespace }}
  labels:
    app-name: elastic-logging
spec:
  selector:
    app-name: elastic-logging
  type: ClusterIP
  ports:
  - name: elastic-log
    port: 9200
    targetPort: 9200
    protocol: TCP
---