kind: Deployment
apiVersion: apps/v1
metadata:
  name: doccano-frontend
  namespace: {{ .Values.global.store_namespace | default "store" }}
  labels:
    k8s-app: doccano-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: doccano-frontend
  template:
    metadata:
      labels:
        app-name: doccano-frontend
    spec:
      containers:
      - name: doccano-frontend
        image: "{{  .Values.global.registry_url }}/doccano-frontend:sha-50db4e9"
        imagePullPolicy: {{ .Values.global.pull_policy_pods | default "IfNotPresent" }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 500Mi
        env:
          - name: API_URL
            value: "http://doccano-backend-service:8000"
          - name: GOOGLE_TRACKING_ID
            value: ""
        volumeMounts:
          - name: static-volume
            mountPath: /static
          - name: media
            mountPath: /media
      volumes:
      - name:  static-volume
        hostPath:
          path: {{ .Values.global.fast_data_dir | default "/home/kaapana" }}/doccano/static
          type: DirectoryOrCreate
      - name:  media
        hostPath:
          path: {{ .Values.global.fast_data_dir | default "/home/kaapana" }}/doccano/media
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: registry-secret