kind: Service
apiVersion: v1
metadata:
  name: doccano-frontend-service
  namespace: {{ .Values.global.store_namespace | default "store" }}
spec:
  selector:
    app-name: doccano-frontend
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: doccano-frontend-ing
  namespace: {{ .Values.global.store_namespace | default "store" }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd
    traefik.ingress.kubernetes.io/preserve-host: "true"
    # ingress.kubernetes.io/custom-request-headers: "Authorization:||cookie:"
    # nginx.ingress.kubernetes.io/enable-cors: "true"
    # nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    # nginx.ingress.kubernetes.io/cors-allow-origin: "https://vm-129-41.cloud.dkfz-heidelberg.de/oauth/"
    # nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    #traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /doccano/
        pathType: ImplementationSpecific
        backend:
          service:
            name: doccano-frontend-service
            port:
              number: 8080
---