
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: base
  #namespace: {{ .Values.global.base_namespace }}
  labels:
    app-name: hello-world
spec:
  selector:
    app-name: hello-world
  ports:
    - name: hw-http
      port: 5000 
      targetPort: 5000
      nodePort: 5000 # only for development!
  type: NodePort # only for development!
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: base
  #namespace: {{ .Values.global.base_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /hello-world
        pathType: ImplementationSpecific
        backend:
          service:
            name: hello-world-service
            port:
              number: 5000
---