---
apiVersion: v1
kind: Service
metadata:
  name: error-pages-service
  namespace: kube-system
spec:
  selector:
    app-name: error-pages
  ports:
    - port: 5000
      name: error-http
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: error-pages-ingress-ip
  namespace: kube-system
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd,kube-system-strip-prefix@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host: error-pages
    http:
      paths:
      - path:
        pathType: ImplementationSpecific
        backend:
          service:
            name: error-pages-service
            port:
              name: error-http
  - host: 
    http:
      paths:
      - path: /error-pages
        pathType: ImplementationSpecific
        backend:
          service:
            name: error-pages-service
            port:
              name: error-http
---
