---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcm-extract-study-id
  namespace: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: dcm-extract-study-id
  template:
    metadata:
      labels:
        app-name: dcm-extract-study-id
    spec:
      containers:
        - name: dcm-extract-study-id-container
          image: {{  .Values.global.registry_url }}/dcm-extract-study-id:0.1.0
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          resources:
            requests:
              memory: 500Mi
            limits:
              memory: 1000Mi
          volumeMounts:
            - name: input-dir
              mountPath: /data
            - name: output-dir
              mountPath: /output
          env:
            - name: OPERATOR_IN_DIR
              value: "/data"            
            - name: OPERATOR_OUT_DIR
              value: "/output"
      volumes:
      - name: input-dir
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/minio/data
          type: DirectoryOrCreate
      
      - name: output-dir
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/minio/output
          type: DirectoryOrCreate

      

