---
global:
    base_namespace: "base"
    default_base_requests_mem: "50Mi"
    default_base_limits_mem: "50Mi"
    # default_base_requests_cpu: 0.5
    # default_base_limits_cpu: 1
    credentials:
        registry_url: ""
        registry_username: ""
        registry_password: ""