kind: Service
apiVersion: v1
metadata:
  name: code-service
  namespace: {{ .Values.global.base_namespace }}
spec:
  selector:
    app-name: code-server
  ports:
    - protocol: TCP
      port: 8080
      name: code-http
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: code-redirect
  namespace: {{ .Values.global.base_namespace }}
spec:
  redirectRegex:
    regex: ^.*/code([^\/]*)$
    replacement: /code/
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: code-server-ingress
  namespace: {{ .Values.global.base_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd,{{ .Values.global.base_namespace }}-code-redirect@kubernetescrd,kube-system-strip-prefix@kubernetescrd
    traefik.ingress.kubernetes.io/preserve-host: "true"
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /code
        pathType: ImplementationSpecific
        backend:
          service:
            name: code-service
            port:
              name: code-http
---
