---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: oauth2-proxy
  template:
    metadata:
      labels:
        app-name: oauth2-proxy
    spec:
      initContainers:
      - name: init
        image: registry.hzdr.de/jonas.scherer/kaapana/service_checker:1.1
        imagePullPolicy:  Always
        env:
          - name: WAIT
            value: "keycloak,keycloak-internal-service.kube-system.svc,443"
          - name: DELAY
            value: "3"
          - name: TIMEOUT
            value: "10"
      containers:
        - name: oauth2-proxy-container
          image: registry.hzdr.de/jonas.scherer/kaapana/oauth2-proxy:7.2.1
          args: ["--email-domain=*"]
          imagePullPolicy:  Always
          env:
            # - name: OAUTH2_PROXY_REDIRECT_URL
            #   value: "https://10.128.129.138/ohif" 
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              # value: "https://10.128.129.138:443/auth/realms/kaapana"
              # value: "https://keycloak-internal-service.kube-system.svc:443/auth/realms/kaapana"
              value: "https://10.128.129.138:8443/auth/realms/kaapana"
            - name: OAUTH2_PROXY_UPSTREAM
              value: "https://10.128.129.138:8443/"
              # value: "http://traefik:8080/"
              # value: "file:///file:///var/www/static/#/"
            - name: OAUTH2_PROXY_PROVIDER
              value: "keycloak-oidc"
            - name: OAUTH2_PROXY_CLIENT_ID
              value: "kaapana"
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: "1c4645f0-e654-45a1-a8b6-cf28790104ea"
            # - name: OAUTH2_PROXY_ALLOWED_ROLE
            #   value: "admin,user"
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: "P7AiFgxZhLuuTZ2iuIQHSnYWrDlU_NVaA-Su1dZ9HMQ="
            # - name: OAUTH2_PROXY_EMAIL_DOMAIN
            #   value: "*"
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: "True"
            - name: OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY
              value: "True"
            - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
              value: "True"
            - name: OAUTH2_PROXY_SKIP_AUTH_PREFLIGHT
              value: "True"
            - name: OAUTH2_PROXY_REVERSE_PROXY
              value: "True"
            # - name: OAUTH2_PROXY_SKIP_OIDC_DISCOVERY
            #   value: "True"
            - name: OAUTH2_PROXY_LOGIN_URL
              value: "https://10.128.129.138:443/auth/realms/kaapana/protocol/openid-connect/auth"
            # - name: OAUTH2_PROXY_OIDC_JWKS_URL
            #   value: "https://keycloak-internal-service.kube-system.svc:443/auth/realms/kaapana/protocol/openid-connect/certs"
            # - name: OAUTH2_PROXY_REDEEM_URL
            #   value: "https://keycloak-internal-service.kube-system.svc:443/auth/realms/kaapana/protocol/openid-connect/token"
            - name: OAUTH2_PROXY_TLS_CERT_FILE
              value: "/ssl/tls.crt"
            - name: OAUTH2_PROXY_TLS_KEY_FILE
              value: "/ssl/tls.key"
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: "0.0.0.0:8080"
            - name: OAUTH2_PROXY_HTTPS_ADDRESS
              value: "0.0.0.0:8443"
            - name: OAUTH2_PROXY_SKIP_AUTH_REGEX
              value: "/auth/*"
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 150Mi
          volumeMounts:
            - name: ssl-config
              mountPath: /ssl
      volumes:
      - name: ssl-config
        secret:
          secretName: certificate
      imagePullSecrets:
      - name: registry-secret
---
