---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: oauth2-proxy
  template:
    metadata:
      labels:
        app-name: oauth2-proxy
    spec:
      initContainers:
      - name: init
        image: {{  .Values.global.registry_url }}/service_checker:1.1
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        env:
          - name: WAIT
            value: "keycloak,keycloak-internal-service.kube-system.svc,443"
          - name: DELAY
            value: "3"
          - name: TIMEOUT
            value: "10"
      containers:
        - name: oauth2-proxy-container
          image: {{  .Values.global.registry_url }}/oauth2-proxy:7.2.1
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          env:
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: "https://10.128.129.138/oauth2/callback" 
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: "http://{{ required "A valid hostname (or fqdn) is required!" $.Values.global.hostname }}:{{ .Values.global.auth_node_port }}/auth/realms/kaapana"
            - name: OAUTH2_PROXY_UPSTREAM
              value: "https://traefik:443"
            - name: OAUTH2_PROXY_PROVIDER
              value: "keycloak-oidc"
            - name: OAUTH2_PROXY_CLIENT
              value: "kaapana"
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: "1c4645f0-e654-45a1-a8b6-cf28790104ea"
            - name: OAUTH2_PROXY_ALLOWED_ROLE
              value: doccano
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: "P7AiFgxZhLuuTZ2iuIQHSnYWrDlU_NVaA-Su1dZ9HMQ="
            - name: OAUTH2_PROXY_EMAIL_DOMAIN
              value: "*"
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: "True"
            - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
              value: "True"
            - name: OAUTH2_PROXY_TLS_CERT_FILE
              value: "/ssl/tls.crt"
            - name: OAUTH2_PROXY_TLS_KEY_FILE
              value: "/ssl/tls.key"
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: "0.0.0.0:8080"
            - name: OAUTH2_PROXY_HTTPS_ADDRESS
              value: "0.0.0.0:8443"
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 150Mi
          volumeMounts:
            - name: config-file
              mountPath: /app
            - name: ssl-config
              mountPath: /ssl
      volumes:
      - name: ssl-config
        secret:
          secretName: certificate
      - name: config-file
        configMap:
          name: oauth2-proxy-config
      imagePullSecrets:
      - name: registry-secret
---
