---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: oauth2-proxy
  template:
    metadata:
      labels:
        app-name: oauth2-proxy
    spec:
      initContainers:
      - name: init
        image: {{  .Values.global.registry_url }}/service_checker:1.1
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        env:
          - name: WAIT
            value: "keycloak,keycloak-internal-service.kube-system.svc,443"
          - name: DELAY
            value: "3"
          - name: TIMEOUT
            value: "10"
      containers:
        - name: oauth2-proxy-container
          image: {{  .Values.global.registry_url }}/oauth2-proxy:7.2.1
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          args:
          - --upstream=https://traefik:443
          - --provider=keycloak-oidc
          - --client-id=kaapana
          - --client-secret=uQBJzc2YDzjRfj2OCT79JDShojeqAK2R
        {{- if ne (.Values.global.https_port | default "443") "443" }}
          - --login-url=https://{{ required "A valid hostname (or fqdn) is required!" $.Values.global.hostname }}:{{ .Values.global.https_port }}/auth/realms/kaapana/protocol/openid-connect/auth
          - --oidc-issuer-url=https://{{ required "A valid hostname (or fqdn) is required!" $.Values.global.hostname }}:{{ .Values.global.https_port }}/auth/realms/kaapana
        {{- else }}
          - --login-url=https://{{ required "A valid hostname (or fqdn) is required!" $.Values.global.hostname }}/auth/realms/kaapana/protocol/openid-connect/auth
          - --oidc-issuer-url=https://{{ required "A valid hostname (or fqdn) is required!" $.Values.global.hostname }}/auth/realms/kaapana
        {{- end }}
          - --redeem-url=https://keycloak-internal-service.kube-system.svc/auth/realms/kaapana/protocol/openid-connect/token
          - --oidc-jwks-url=https://keycloak-internal-service.kube-system.svc/auth/realms/kaapana/protocol/openid-connect/certs
          - --profile-url=https://keycloak-internal-service.kube-system.svc/auth/realms/kaapana/protocol/openid-connect/userinfo
          - --cookie-secret=P7AiFgxZhLuuTZ2iuIQHSnYWrDlU_NVaA-Su1dZ9HMQ=
          - --skip-auth-regex=/auth/*
          - --http-address=0.0.0.0:8080
          - --https-address=0.0.0.0:8443
          - --tls-cert-file=/ssl/tls.crt 
          - --tls-key-file=/ssl/tls.key
          - --skip-oidc-discovery
          - --insecure-oidc-allow-unverified-email 
          - --insecure-oidc-skip-nonce
          - --skip-provider-button
          - --skip-auth-preflight
          - --show-debug-on-error
          - --set-authorization-header
          - --ssl-insecure-skip-verify
          - --ssl-upstream-insecure-skip-verify
          - --force-https
          - --set-xauthrequest
          - --pass-access-token 
          - --email-domain=*
          # - --metrics-address=/metrics
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 150Mi
          volumeMounts:
            - name: ssl-config
              mountPath: /ssl
      volumes:
      - name: ssl-config
        secret:
          secretName: certificate
      imagePullSecrets:
      - name: registry-secret
---
